name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # Otherwise our annotated tag is not fetched and we cannot get correct version

      - name: Get release info
        run: git tag --format '%(contents:body)' --points-at > release-body.txt

      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          bodyFile: release-body.txt
